version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:17-jdk

jobs:
  build:
    executor: docker-executor
    steps:

      - add_ssh_keys:
          fingerprints:
            - "ce:60:dc:87:cd:91:06:1c:e5:4d:f6:bf:c5:02:a5:61"

      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t nicolaszelarayan/backend-reciclarg:$CIRCLE_SHA1 .
      - run: docker push nicolaszelarayan/backend-reciclarg:$CIRCLE_SHA1

      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "cd /home/nicolas_zelarayan/backend/Reciclarg-Backend/ && sudo git pull"
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "sudo docker stop backend_container || true"
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "sudo docker rm backend_container || true"
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "sudo docker run -p 8090:8080 -d --name backend_container nicolaszelarayan/backend-reciclarg:$CIRCLE_SHA1"
